spring:
  application:
    name: msagent
  datasource:
    url: jdbc:h2:mem:agent_db
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 0

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: msagent
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
