spring:
  application:
    name: msagent
  datasource:
    url: jdbc:h2:mem:agent_db
    driver-class-name: org.h2.Driver
    username: sa

  rabbitmq:
    port: 5672
    username: guest
    password: guest
    host: localhost


  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 0

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}



mq:
  queues:
    hero-registration: hero-registration